using Application.Dto_s;
using Application.Dto_s.CaseDtos;
using Application.Dto_s.CourtDto_s;
using Application.Dto_s.User;
using AutoMapper;
using Domain.Entites;
using Infrastrcuture.Auth;
using Infrastrcuture.Users;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;

namespace Infrastrcuture.Mappers
{
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {

            #region Mapping Entites into DTO's
            
            
            //Mapping Found Application User Entity to the DTO
            CreateMap<ApplicationUser, ApplicationUserReadDto>();
            CreateMap<ApplicationUser, UserReadDto>()
                .ForMember(dest => dest.DisplayName, opt => opt.MapFrom(src => src.displayName))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.isActive));
                //.ForMember(dest => dest.IsDeleted, opt => opt.MapFrom(src => src.isDeleted));


            #endregion

            #region Mapping DTO's To Entites


            //Mapping UserDTO to User Entity
            CreateMap<ApplicationUserReadDto, ApplicationUser>()
                        .ForMember(dest => dest.PasswordHash, opt => opt.MapFrom(src => src.PasswordHash));

            #endregion

            #region Case Entity Mapping

            // Mapping CaseAddDto to Case Entity
            CreateMap<CaseAddDto, Case>()
                .ForMember(dest => dest.id, opt => opt.Ignore()) // Ignore ID as it will be generated
                .ForMember(dest => dest.createdBy, opt => opt.MapFrom(src => src.createdBy)) // Map from DTO
                .ForMember(dest => dest.createdAt, opt => opt.Ignore()) // Will be set by service layer
                .ForMember(dest => dest.updatedBy, opt => opt.Ignore())
                .ForMember(dest => dest.updatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.isDeleted, opt => opt.MapFrom(src => false)) // Default to not deleted
                .ForMember(dest => dest.rowVersion, opt => opt.Ignore())
                .ForMember(dest => dest.deletedBy, opt => opt.Ignore())
                .ForMember(dest => dest.deletedAt, opt => opt.Ignore())
                .ForMember(dest => dest.deletionReason, opt => opt.Ignore())
                .ForMember(dest => dest.versionNo, opt => opt.MapFrom(src => 1)) // Initial version
                .ForMember(dest => dest.approved, opt => opt.MapFrom(src => false)) // Default to not approved
                .ForMember(dest => dest.court, opt => opt.Ignore()) // Navigation property
                .ForMember(dest => dest.caseType, opt => opt.Ignore()) // Navigation property
                .ForMember(dest => dest.caseTopic, opt => opt.Ignore()) // Navigation property
                .ForMember(dest => dest.caseDocuments, opt => opt.Ignore()) // Collection navigation property
                .ForMember(dest => dest.assignments, opt => opt.Ignore()) // Collection navigation property
                .ForMember(dest => dest.claims, opt => opt.Ignore()) // Collection navigation property
                .ForMember(dest => dest.events, opt => opt.Ignore()) // Collection navigation property
                .ForMember(dest => dest.taskItems, opt => opt.Ignore()) // Collection navigation property
                .ForMember(dest => dest.hearings, opt => opt.Ignore()) // Collection navigation property
                .ForMember(dest => dest.CaseLitigants, opt => opt.Ignore()); // Collection navigation property

            // Mapping Case Entity to CaseAddDto
            CreateMap<Case, CaseAddDto>();

            #endregion

            #region Case Assignment Entity Mapping

            // Map from DTO to Entity
            CreateMap<CaseAssignmentDto, CaseAssignment>()
                .ForMember(dest => dest.id, opt => opt.Ignore()) // Id will be generated by the DB
                .ForMember(dest => dest.createdAt, opt => opt.Ignore()) // Handled by service layer
                .ForMember(dest => dest.updatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.isDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.rowVersion, opt => opt.Ignore())
                .ForMember(dest => dest.Case, opt => opt.Ignore()); // Avoid circular mapping for now

            // Map from Entity to DTO
            CreateMap<CaseAssignment, CaseAssignmentDto>()
                .ForMember(dest => dest.createdBy, opt => opt.MapFrom(src => src.createdBy))
                .ForMember(dest => dest.assignedUserId, opt => opt.MapFrom(src => src.assignedUserId))
                .ForMember(dest => dest.assignedUserRole, opt => opt.MapFrom(src => src.assignedUserRole))
                .ForMember(dest => dest.assignerId, opt => opt.MapFrom(src => src.assignerId))
                .ForMember(dest => dest.isCurrent, opt => opt.MapFrom(src => src.isCurrent))
                .ForMember(dest => dest.notes, opt => opt.MapFrom(src => src.notes))
                .ForMember(dest => dest.CaseId, opt => opt.MapFrom(src => src.CaseId));

            #endregion

            #region Case Topic Entity Mapping

            // Map from DTO to Entity
            CreateMap<CaseTopicAddDto, CaseTopic>()
                .ForMember(dest => dest.id, opt => opt.Ignore()) // Id يتم توليده في DB
                .ForMember(dest => dest.createdAt, opt => opt.Ignore()) // الوقت يتم تعيينه في Service Layer
                .ForMember(dest => dest.updatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.isDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.rowVersion, opt => opt.Ignore())
                .ForMember(dest => dest.Cases, opt => opt.Ignore()) // تجاهل قائمة القضايا لتجنب المشاكل

            // Map from Entity to DTO
            .ReverseMap(); // يسمح بعكس التحويل تلقائيًا إذا احتجنا

            #endregion

            #region Case Type Entity Mapping

            // Map from DTO to Entity
            CreateMap<CaseTypeAddDto, CaseType>()
                .ForMember(dest => dest.id, opt => opt.Ignore()) // Id يتم توليده في DB
                .ForMember(dest => dest.createdAt, opt => opt.Ignore()) // الوقت يتم تعيينه في Service Layer
                .ForMember(dest => dest.updatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.isDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.rowVersion, opt => opt.Ignore())
                .ForMember(dest => dest.Cases, opt => opt.Ignore()) // تجاهل قائمة القضايا لتجنب المشاكل

            // Map from Entity to DTO
            .ReverseMap(); // يسمح بعكس التحويل تلقائيًا إذا احتجنا

            #endregion

            #region Case Litigant Role Entity Mapping

            // Map from DTO to Entity
            CreateMap<CaseLitigantRoleDto, CaseLitigantRole>()
                .ForMember(dest => dest.id, opt => opt.Ignore()) // Id يتم توليده في DB
                .ForMember(dest => dest.createdAt, opt => opt.Ignore()) // الوقت يتم تعيينه في Service Layer
                .ForMember(dest => dest.updatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.isDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.rowVersion, opt => opt.Ignore())
                .ForMember(dest => dest.CaseLitigants, opt => opt.Ignore()) // تجاهل قائمة القضايا لتجنب المشاكل

            // Map from Entity to DTO
            .ReverseMap(); // يسمح بعكس التحويل تلقائيًا إذا احتجنا


            #endregion

            #region Litigant Entity Mapping

            // Map from DTO to Entity
            CreateMap<LitigantDto, Litigant>()
                .ForMember(dest => dest.id, opt => opt.Ignore()) // Id يتم توليده من DB
                .ForMember(dest => dest.createdAt, opt => opt.Ignore())
                .ForMember(dest => dest.updatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.isDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.rowVersion, opt => opt.Ignore())
                .ForMember(dest => dest.CaseLitigants, opt => opt.Ignore()); // لتجنب مشاكل التحويل للقائمة

            // Map from Entity to DTO
            CreateMap<Litigant, LitigantDto>()
                .ForMember(dest => dest.createdBy, opt => opt.MapFrom(src => src.createdBy))
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.id))
                .ForMember(dest => dest.firstNameAR, opt => opt.MapFrom(src => src.firstNameAR))
                .ForMember(dest => dest.lastNameAR, opt => opt.MapFrom(src => src.lastNameAR))
                .ForMember(dest => dest.firstNameEN, opt => opt.MapFrom(src => src.firstNameEN))
                .ForMember(dest => dest.lastNameEN, opt => opt.MapFrom(src => src.lastNameEN))
                .ForMember(dest => dest.nationalIdNumber, opt => opt.MapFrom(src => src.nationalIdNumber))
                .ForMember(dest => dest.nationalIdType, opt => opt.MapFrom(src => src.nationalIdType))
                .ForMember(dest => dest.phoneNumber, opt => opt.MapFrom(src => src.phoneNumber))
                .ForMember(dest => dest.address, opt => opt.MapFrom(src => src.address))
                .ForMember(dest => dest.email, opt => opt.MapFrom(src => src.email))
                .ForMember(dest => dest.country, opt => opt.MapFrom(src => src.country));

            #endregion

            #region Case Litigant Entity Mapping

            CreateMap<CaseLtitgantDto, CaseLitigant>()
         .ForMember(dest => dest.Case, opt => opt.Ignore()) // تجاهل الـ navigation property
         .ForMember(dest => dest.Litigant, opt => opt.Ignore())
         .ForMember(dest => dest.Role, opt => opt.Ignore())
         .ForMember(dest => dest.id, opt => opt.Ignore()) // Id يتم توليده في DB
         .ForMember(dest => dest.createdAt, opt => opt.Ignore())
         .ForMember(dest => dest.updatedAt, opt => opt.Ignore())
         .ForMember(dest => dest.isDeleted, opt => opt.Ignore())
         .ForMember(dest => dest.rowVersion, opt => opt.Ignore());

            // Map from Entity to DTO
            CreateMap<CaseLitigant, CaseLtitgantDto>()
                .ForMember(dest => dest.caseId, opt => opt.MapFrom(src => src.caseId))
                .ForMember(dest => dest.litigantId, opt => opt.MapFrom(src => src.litigantId))
                .ForMember(dest => dest.roleId, opt => opt.MapFrom(src => src.roleId))
                .ForMember(dest => dest.createdBy, opt => opt.MapFrom(src => src.createdBy));

            #endregion

            #region Case Read Entity Mapping

            CreateMap<Case, CaseReadDto>()
                    .ForMember(dest => dest.CourtName , opt => opt.MapFrom(src => src.court.nameAR))
                    .ForMember(dest => dest.CaseId , opt => opt.MapFrom(src => src.id))
                    .ForMember(dest => dest.CourtGrade, opt => opt.MapFrom(src => src.court.courtGrade.nameAR))
                    .ForMember(dest => dest.CaseTitle, opt => opt.MapFrom(src => src.caseTopic.topicName))
                    .ForMember(dest => dest.CaseType, opt => opt.MapFrom(src => src.caseType.typeName))
                    .ForMember(dest => dest.ClosingReason, opt => opt.MapFrom(src => !string.IsNullOrEmpty(src.EndReport) ? src.EndReport : "غير متاح"));

            #endregion

            #region Case Entity Full Data Read

            CreateMap<Case, CaseFullDataReadDto>()
               .ForMember(dest => dest.addtionDate, opt => opt.MapFrom(src => src.createdAt.ToString("yyyy-MM-dd"))) // assuming BaseEntity has CreatedAt
               .ForMember(dest => dest.CaseId, opt => opt.MapFrom(src => src.id))
               .ForMember(dest => dest.lastModificationDate, opt => opt.MapFrom(src => src.updatedAt != null ? src.updatedAt.Value.ToString("yyyy-MM-dd") : "لم يتم التعديل على القضية حتى الان"))
               .ForMember(dest => dest.RegistererName, opt => opt.MapFrom(src => src.createdBy != null ? src.createdBy : "غير محدد"))
               .ForMember(dest => dest.modifier, opt => opt.MapFrom(src => src.updatedBy != null ? src.updatedBy : "غير محدد"))
               .ForMember(dest => dest.CaseDate, opt => opt.MapFrom(src => src.caseDate))
               .ForMember(dest => dest.caseNumber, opt => opt.MapFrom(src => src.caseNumber))
               .ForMember(dest => dest.caseNumberInCourt, opt => opt.MapFrom(src => src.caseNumberInCourt))
               .ForMember(dest => dest.caseNumberInCourtComputer, opt => opt.MapFrom(src => src.caseNumberInCourtComputer))
               .ForMember(dest => dest.caseNumberInClaim, opt => opt.MapFrom(src => src.caseNumberInClaim))
               .ForMember(dest => dest.status, opt => opt.MapFrom(src => src.status))
               .ForMember(dest => dest.approved, opt => opt.MapFrom(src => src.approved))
               .ForMember(dest => dest.governate, opt => opt.MapFrom(src => src.governate))
               .ForMember(dest => dest.state, opt => opt.MapFrom(src => src.state))
               .ForMember(dest => dest.village, opt => opt.MapFrom(src => src.village))
               .ForMember(dest => dest.description, opt => opt.MapFrom(src => src.description))
              .ForMember(dest => dest.CourtName, opt => opt.MapFrom(src => src.court.nameAR))
                    .ForMember(dest => dest.CourtGrade, opt => opt.MapFrom(src => src.court.courtGrade.nameAR))
                    .ForMember(dest => dest.caseTitle, opt => opt.MapFrom(src => src.caseTopic.topicName))
                    .ForMember(dest => dest.CaseType, opt => opt.MapFrom(src => src.caseType.typeName));

            #endregion

            #region Case Litigants Full Data Mapping

            CreateMap<CaseLitigant, LitigantReadDto>()
               .ForMember(dest => dest.name, opt => opt.MapFrom(src =>
                   src.Litigant.isOrganisation
                       ? src.Litigant.firstNameAR // اسم المؤسسة
                       : $"{src.Litigant.firstNameAR} {src.Litigant.lastNameAR}".Trim())) // اسم الشخص الكامل
               .ForMember(dest => dest.isOrganisation, opt => opt.MapFrom(src => src.Litigant.isOrganisation ? "منظمة" : "فرد"))
               .ForMember(dest => dest.id, opt => opt.MapFrom(src => src.Litigant.id))
               .ForMember(dest => dest.NationalIdNumber, opt => opt.MapFrom(src => src.Litigant.nationalIdNumber))
               .ForMember(dest => dest.NationalIdType, opt => opt.MapFrom(src => src.Litigant.nationalIdType))
               .ForMember(dest => dest.CaseId, opt => opt.MapFrom(src => src.Case.id))
               .ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role.roleName));

            #endregion

            #region Lawyer Entity Mapping

            CreateMap<ApplicationUser, LawyerReadDto>()
              .ForMember(dest => dest.UserName, opt => opt.MapFrom(src => src.UserName)) // assuming BaseEntity has CreatedAt
              .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.displayName))
              .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email))
              .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id));


            #endregion

            #region Lawyer Entity Full data mapping

            CreateMap<Lawyer, LawyerFullDataReadDto>()
            .ForMember(dest => dest.UserName, opt => opt.MapFrom(src => src.UserName)) // assuming BaseEntity has CreatedAt
            .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.displayName))
            .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email))
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.creationDate, opt => opt.MapFrom(src => src.CreatedAt.ToString("yyyy-MM-dd")))
            .ForMember(dest => dest.creator, opt => opt.MapFrom(src => src.CreateedBy))
            .ForMember(dest => dest.modificationDate, opt => opt.MapFrom(src => src.ModifiedAt != null ? src.ModifiedAt.Value.ToString("yyyy-MM-dd") : "لم يتم اضافة تعديلات مؤخرا"))
            .ForMember(dest => dest.modifier, opt => opt.MapFrom(src => src.ModifiedBy != null ? src.ModifiedBy.ToString() : "لم يتم اضافة تعديلات مؤخرا"))
            .ForMember(dest => dest.phoneNumber, opt => opt.MapFrom(src => src.PhoneNumber != null ? src.PhoneNumber : "رقم الهاتف غير مسجل لدينا"))
            .ForMember(dest => dest.numberOfClosedCases, opt => opt.MapFrom(src => src.numberOfEndedCases))
            .ForMember(dest => dest.numberOfPendingCases, opt => opt.MapFrom(src => src.numberOfPendingCases))
            .ForMember(dest => dest.numberOfCurrentCases, opt => opt.MapFrom(src => src.numberOfCurrentCases));


            #endregion
        }
    }
}
