// <auto-generated />
using System;
using Infrastrcuture.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastrcuture.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250928041252_PhaseOneCreatingAllCaseRelatedEntitesAndUsersTablesAndAlsoApplingDataseeding")]
    partial class PhaseOneCreatingAllCaseRelatedEntitesAndUsersTablesAndAlsoApplingDataseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entites.Case", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("approved")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("caseDate")
                        .HasColumnType("date");

                    b.Property<string>("caseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caseNumberInClaim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caseNumberInCourt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caseNumberInCourtComputer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("caseTopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("caseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("courtGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("courtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("governate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.Property<string>("village")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("caseTopicId");

                    b.HasIndex("caseTypeId");

                    b.HasIndex("courtGradeId");

                    b.HasIndex("courtId");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            id = new Guid("80808080-8080-8080-8080-808080808080"),
                            approved = true,
                            caseDate = new DateOnly(2024, 1, 15),
                            caseNumber = "2024/001",
                            caseNumberInClaim = "CLAIM-2024-001",
                            caseNumberInCourt = "12345/2024",
                            caseNumberInCourtComputer = "2024001234",
                            caseTopicId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            caseTypeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            courtGradeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            courtId = new Guid("44444444-4444-4444-4444-444444444444"),
                            createdAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            description = "قضية تعويض عن ضرر مادي ومعنوي",
                            governate = "القاهرة",
                            isDeleted = false,
                            state = "مصر",
                            status = "Registered",
                            versionNo = 1,
                            village = "وسط البلد"
                        },
                        new
                        {
                            id = new Guid("90909090-9090-9090-9090-909090909090"),
                            approved = false,
                            caseDate = new DateOnly(2024, 2, 20),
                            caseNumber = "2024/002",
                            caseNumberInClaim = "CLAIM-2024-002",
                            caseNumberInCourt = "54321/2024",
                            caseNumberInCourtComputer = "2024002345",
                            caseTopicId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            caseTypeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            courtGradeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            courtId = new Guid("55555555-5555-5555-5555-555555555555"),
                            createdAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            description = "قضية طلاق ونفقة",
                            governate = "الإسكندرية",
                            isDeleted = false,
                            state = "مصر",
                            status = "UnderStudy",
                            versionNo = 1,
                            village = "سيدي بشر"
                        });
                });

            modelBuilder.Entity("Domain.Entites.CaseAssignment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("assignedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("assignedUserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("assignerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CaseId");

                    b.HasIndex("assignedUserId");

                    b.HasIndex("assignerId");

                    b.ToTable("CasesAssignments");
                });

            modelBuilder.Entity("Domain.Entites.CaseDocument", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FileAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("docCategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("docType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("uniqueNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CaseId");

                    b.ToTable("CasesDocuments");

                    b.HasData(
                        new
                        {
                            id = new Guid("1f6c9b63-9e45-421f-915c-f45c7b65c7c7"),
                            CaseId = new Guid("80808080-8080-8080-8080-808080808080"),
                            VsId = "VS002",
                            createdAt = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            description = "مذكرة الدفاع الأولى",
                            docCategoryCode = "DEFENSE",
                            docType = "مذكرة دفاع",
                            isDeleted = false,
                            uniqueNo = 2,
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("2d2f1a45-bd6e-4c2c-aea1-7c37c68b68b6"),
                            CaseId = new Guid("90909090-9090-9090-9090-909090909090"),
                            VsId = "VS003",
                            createdAt = new DateTime(2024, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            description = "طلب طلاق ونفقة",
                            docCategoryCode = "DIVORCE",
                            docType = "طلب طلاق",
                            isDeleted = false,
                            uniqueNo = 1,
                            versionNo = 1
                        });
                });

            modelBuilder.Entity("Domain.Entites.CaseEvent", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CaseId");

                    b.ToTable("CasesEvents");

                    b.HasData(
                        new
                        {
                            id = new Guid("f6f6f6f6-f6f6-4f6f-a6f6-f6f6f6f6f6f6"),
                            CaseId = new Guid("80808080-8080-8080-8080-808080808080"),
                            createdAt = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            details = "تم تسجيل القضية في المحكمة الابتدائية",
                            eventType = "تسجيل القضية",
                            isDeleted = false,
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("a17f7c85-8b64-4a6d-9f59-4f3d8f18d3d3"),
                            CaseId = new Guid("80808080-8080-8080-8080-808080808080"),
                            createdAt = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            details = "تم إيداع مذكرة الدفاع الأولى",
                            eventType = "إيداع مذكرة دفاع",
                            isDeleted = false,
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("c1f4de2a-0d94-45ff-8f42-32e6b6d7b6d7"),
                            CaseId = new Guid("90909090-9090-9090-9090-909090909090"),
                            createdAt = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            details = "تم تسجيل قضية الطلاق والنفقة",
                            eventType = "تسجيل القضية",
                            isDeleted = false,
                            versionNo = 1
                        });
                });

            modelBuilder.Entity("Domain.Entites.CaseLitigant", b =>
                {
                    b.Property<Guid>("caseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("litigantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("roleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("caseId", "litigantId", "roleId");

                    b.HasIndex("litigantId");

                    b.HasIndex("roleId");

                    b.ToTable("CaseLitigant");

                    b.HasData(
                        new
                        {
                            caseId = new Guid("80808080-8080-8080-8080-808080808080"),
                            litigantId = new Guid("50505050-5050-5050-5050-505050505050"),
                            roleId = new Guid("10101010-1010-1010-1010-101010101010"),
                            createdAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            id = new Guid("00000000-0000-0000-0000-000000000000"),
                            isDeleted = false,
                            versionNo = 0
                        },
                        new
                        {
                            caseId = new Guid("80808080-8080-8080-8080-808080808080"),
                            litigantId = new Guid("70707070-7070-7070-7070-707070707070"),
                            roleId = new Guid("20202020-2020-2020-2020-202020202020"),
                            createdAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            id = new Guid("00000000-0000-0000-0000-000000000000"),
                            isDeleted = false,
                            versionNo = 0
                        },
                        new
                        {
                            caseId = new Guid("90909090-9090-9090-9090-909090909090"),
                            litigantId = new Guid("60606060-6060-6060-6060-606060606060"),
                            roleId = new Guid("10101010-1010-1010-1010-101010101010"),
                            createdAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            id = new Guid("00000000-0000-0000-0000-000000000000"),
                            isDeleted = false,
                            versionNo = 0
                        },
                        new
                        {
                            caseId = new Guid("90909090-9090-9090-9090-909090909090"),
                            litigantId = new Guid("60606060-6060-6060-6060-606060606060"),
                            roleId = new Guid("20202020-2020-2020-2020-202020202020"),
                            createdAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            id = new Guid("00000000-0000-0000-0000-000000000000"),
                            isDeleted = false,
                            versionNo = 0
                        });
                });

            modelBuilder.Entity("Domain.Entites.CaseLitigantRole", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("CaseLitigantRole");

                    b.HasData(
                        new
                        {
                            id = new Guid("10101010-1010-1010-1010-101010101010"),
                            createdAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isDeleted = false,
                            roleName = "مدعى",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("20202020-2020-2020-2020-202020202020"),
                            createdAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isDeleted = false,
                            roleName = "مدعى عليه",
                            versionNo = 1
                        });
                });

            modelBuilder.Entity("Domain.Entites.CaseTopic", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("topicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("CasesTopics");

                    b.HasData(
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            createdAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isDeleted = false,
                            topicName = "تعويضات",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            createdAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isDeleted = false,
                            topicName = "طلاق",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            createdAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isDeleted = false,
                            topicName = "نفقة",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            createdAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isDeleted = false,
                            topicName = "عقد عمل",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            createdAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isDeleted = false,
                            topicName = "ميراث",
                            versionNo = 1
                        });
                });

            modelBuilder.Entity("Domain.Entites.CaseType", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("typeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("CasesTypes");

                    b.HasData(
                        new
                        {
                            id = new Guid("77777777-7777-7777-7777-777777777777"),
                            createdAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isDeleted = false,
                            typeName = "قضية مدنية",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("88888888-8888-8888-8888-888888888888"),
                            createdAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isDeleted = false,
                            typeName = "قضية جنائية",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("99999999-9999-9999-9999-999999999999"),
                            createdAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isDeleted = false,
                            typeName = "قضية تجارية",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            createdAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isDeleted = false,
                            typeName = "قضية عمالية",
                            versionNo = 1
                        });
                });

            modelBuilder.Entity("Domain.Entites.Court", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("courtGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("nameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("courtGradeId");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            id = new Guid("44444444-4444-4444-4444-444444444444"),
                            city = "القاهرة",
                            courtGradeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            createdAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isActive = true,
                            isDeleted = false,
                            nameAR = "محكمة القاهرة الابتدائية",
                            nameEN = "Cairo Primary Court",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("55555555-5555-5555-5555-555555555555"),
                            city = "الإسكندرية",
                            courtGradeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            createdAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isActive = true,
                            isDeleted = false,
                            nameAR = "محكمة الإسكندرية الابتدائية",
                            nameEN = "Alexandria Primary Court",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("66666666-6666-6666-6666-666666666666"),
                            city = "القاهرة",
                            courtGradeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            createdAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isActive = true,
                            isDeleted = false,
                            nameAR = "محكمة القاهرة الاستئنافية",
                            nameEN = "Cairo Court of Appeal",
                            versionNo = 1
                        });
                });

            modelBuilder.Entity("Domain.Entites.CourtGrade", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("nameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("CourtsGrades");

                    b.HasData(
                        new
                        {
                            id = new Guid("11111111-1111-1111-1111-111111111111"),
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isActive = true,
                            isDeleted = false,
                            nameAR = "محكمة النقض",
                            nameEN = "Court of Cassation",
                            order = "1",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("22222222-2222-2222-2222-222222222222"),
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isActive = true,
                            isDeleted = false,
                            nameAR = "محكمة الاستئناف",
                            nameEN = "Court of Appeal",
                            order = "2",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("33333333-3333-3333-3333-333333333333"),
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isActive = true,
                            isDeleted = false,
                            nameAR = "المحكمة الابتدائية",
                            nameEN = "Primary Court",
                            order = "3",
                            versionNo = 1
                        });
                });

            modelBuilder.Entity("Domain.Entites.Hearing", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("currentHearingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("nextHearingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("number")
                        .HasColumnType("int");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("scheduledBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CaseId");

                    b.ToTable("Hearings");

                    b.HasData(
                        new
                        {
                            id = new Guid("3a42d6d5-bc3f-4b85-bc1c-dc24a8d24a8d"),
                            CaseId = new Guid("80808080-8080-8080-8080-808080808080"),
                            createdAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            currentHearingDate = new DateTime(2024, 3, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false,
                            location = "قاعة المحكمة رقم 1",
                            nextHearingDate = new DateTime(2024, 4, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            notes = "جلسة استماع أولى",
                            number = 1,
                            scheduledBy = "Lawyer",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("4c56f3f7-78b6-4f9f-8e3d-4f68b3f68b3f"),
                            CaseId = new Guid("90909090-9090-9090-9090-909090909090"),
                            createdAt = new DateTime(2024, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            currentHearingDate = new DateTime(2024, 3, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false,
                            location = "قاعة المحكمة رقم 2",
                            nextHearingDate = new DateTime(2024, 4, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            notes = "جلسة أولى لقضية الطلاق والنفقة",
                            number = 1,
                            scheduledBy = "Lawyer",
                            versionNo = 1
                        });
                });

            modelBuilder.Entity("Domain.Entites.Judgement", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("hearingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("verdictDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("verdictText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("hearingId");

                    b.ToTable("Judgements");

                    b.HasData(
                        new
                        {
                            id = new Guid("5b12e4e4-2f91-40c3-8d93-63e56f56f56f"),
                            createdAt = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            hearingId = new Guid("3a42d6d5-bc3f-4b85-bc1c-dc24a8d24a8d"),
                            isApproved = true,
                            isDeleted = false,
                            verdictDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            verdictText = "حكمت المحكمة بالتعويض عن الضرر المادي والمعنوي",
                            versionNo = 1
                        });
                });

            modelBuilder.Entity("Domain.Entites.JudgementOrder", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("approvalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("isInternal")
                        .HasColumnType("bit");

                    b.Property<Guid>("judgementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("orderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("judgementId");

                    b.ToTable("JudgementsOrders");

                    b.HasData(
                        new
                        {
                            id = new Guid("7e41c2c2-89f7-4b92-b9c3-32f6d9f6d9f6"),
                            approvalStatus = "موافق عليه",
                            createdAt = new DateTime(2024, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            isDeleted = false,
                            isInternal = false,
                            judgementId = new Guid("5b12e4e4-2f91-40c3-8d93-63e56f56f56f"),
                            orderType = "تعويض مالي",
                            versionNo = 1
                        });
                });

            modelBuilder.Entity("Domain.Entites.LegalClaim", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<string>("claimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("legalBasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CaseId");

                    b.ToTable("LegalClaims");

                    b.HasData(
                        new
                        {
                            id = new Guid("d4d4d4d4-d4d4-d4d4-d4d4-d4d4d4d4d4d4"),
                            CaseId = new Guid("80808080-8080-8080-8080-808080808080"),
                            amount = 50000.0,
                            claimType = "تعويض مادي",
                            createdAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            currency = "جنيه مصري",
                            isDeleted = false,
                            legalBasis = "المادة 163 من القانون المدني",
                            notes = "تعويض عن الأضرار المادية والمعنوية",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            CaseId = new Guid("90909090-9090-9090-9090-909090909090"),
                            amount = 2000.0,
                            claimType = "نفقة شهرية",
                            createdAt = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            currency = "جنيه مصري",
                            isDeleted = false,
                            legalBasis = "قانون الأحوال الشخصية",
                            notes = "نفقة شهرية للأطفال",
                            versionNo = 1
                        });
                });

            modelBuilder.Entity("Domain.Entites.Litigant", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstNameAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstNameEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("isOrganisation")
                        .HasColumnType("bit");

                    b.Property<string>("lastNameAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastNameEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationalIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationalIdType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Litigants");

                    b.HasData(
                        new
                        {
                            id = new Guid("50505050-5050-5050-5050-505050505050"),
                            address = "شارع التحرير، القاهرة",
                            country = "مصر",
                            createdAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            email = "ahmed.mohamed@email.com",
                            firstNameAR = "أحمد",
                            firstNameEN = "Ahmed",
                            isDeleted = false,
                            isOrganisation = false,
                            lastNameAR = "محمد",
                            lastNameEN = "Mohamed",
                            nationalIdNumber = "12345678901234",
                            nationalIdType = "رقم قومي",
                            phoneNumber = "01234567890",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("60606060-6060-6060-6060-606060606060"),
                            address = "شارع الهرم، الجيزة",
                            country = "مصر",
                            createdAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            email = "fatma.ali@email.com",
                            firstNameAR = "فاطمة",
                            firstNameEN = "Fatma",
                            isDeleted = false,
                            isOrganisation = false,
                            lastNameAR = "علي",
                            lastNameEN = "Ali",
                            nationalIdNumber = "98765432109876",
                            nationalIdType = "رقم قومي",
                            phoneNumber = "01987654321",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("70707070-7070-7070-7070-707070707070"),
                            address = "ميدان التحرير، القاهرة",
                            country = "مصر",
                            createdAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            email = "company@email.com",
                            firstNameAR = "شركة الاخوة المتحدون للتوريدات",
                            firstNameEN = "United Pros",
                            isDeleted = false,
                            isOrganisation = true,
                            lastNameAR = "ش.م.م",
                            lastNameEN = "A.R.E",
                            nationalIdNumber = "12345678901234",
                            nationalIdType = "سجل تجاري",
                            phoneNumber = "02234567890",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("88888888-8888-8888-8888-888888888888"),
                            address = "ميدان التحرير، القاهرة",
                            country = "مصر",
                            createdAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            email = "company2@email.com",
                            firstNameAR = "شركة النصر للسيارات",
                            firstNameEN = "Nasr Auto",
                            isDeleted = false,
                            isOrganisation = true,
                            lastNameAR = "ش.م.م",
                            lastNameEN = "A.R.E",
                            nationalIdNumber = "12348756901234",
                            nationalIdType = "رقم قومي",
                            phoneNumber = "02234567890",
                            versionNo = 1
                        });
                });

            modelBuilder.Entity("Domain.Entites.TaskItem", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("assignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dueTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("rowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CaseId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            id = new Guid("9a42e5e5-1b67-4f93-8a23-12f6a7f6a7f6"),
                            CaseId = new Guid("80808080-8080-8080-8080-808080808080"),
                            assignedTo = "محامي",
                            createdAt = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            dueTo = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false,
                            status = "مكتمل",
                            title = "إعداد مذكرة الدفاع",
                            versionNo = 1
                        },
                        new
                        {
                            id = new Guid("af31b6b6-27f3-4c42-9c73-22c6c8c6c8c6"),
                            CaseId = new Guid("90909090-9090-9090-9090-909090909090"),
                            assignedTo = "باحث قانوني",
                            createdAt = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "System",
                            dueTo = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false,
                            status = "قيد التنفيذ",
                            title = "جمع المستندات المطلوبة",
                            versionNo = 1
                        });
                });

            modelBuilder.Entity("Infrastrcuture.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("displayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = "7a6a2d33-5d69-4d1e-9ef3-000000000001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b6f994c7-3b9c-45d9-8f3e-222222222222",
                            CreatedAt = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateedBy = "Seed",
                            Email = "AhmedHisham@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "AHMEDHISHAM@GMAIL.COM",
                            NormalizedUserName = "AHMEDHISHAM@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGtb0i72XFlbS89FQQKfSVnqluD7460Y6sHBWpYwOE97OBwoCL4WDlVr1r8jjCgezw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6d7c0db6-89af-4e38-bc2e-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "AhmedHisham@gmail.com",
                            displayName = "Ahmed Hisham",
                            isActive = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = "7a6a2d33-5d69-4d1e-9ef3-000000000003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b6f994c7-3b9c-45d9-8f3e-444444444444",
                            CreatedAt = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateedBy = "Seed",
                            Email = "hejab99099@hiepth.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "HEJAB99099@HIEPTH.COM",
                            NormalizedUserName = "HEJAB99099@HIEPTH.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGtb0i72XFlbS89FQQKfSVnqluD7460Y6sHBWpYwOE97OBwoCL4WDlVr1r8jjCgezw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6d7c0db6-89af-4e38-bc2e-333333333333",
                            TwoFactorEnabled = false,
                            UserName = "hejab99099@hiepth.com",
                            displayName = "Ahmed Ayman",
                            isActive = true,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "7a6a2d33-5d69-4d1e-9ef3-000000000001",
                            RoleId = "f5a0a1f3-5f7c-4a35-9b0e-0a9c4f0b0001"
                        },
                        new
                        {
                            UserId = "7a6a2d33-5d69-4d1e-9ef3-000000000002",
                            RoleId = "f5a0a1f3-5f7c-4a35-9b0e-0a9c4f0b0002"
                        },
                        new
                        {
                            UserId = "7a6a2d33-5d69-4d1e-9ef3-000000000003",
                            RoleId = "f5a0a1f3-5f7c-4a35-9b0e-0a9c4f0b0003"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Infrastrcuture.Users.Lawyer", b =>
                {
                    b.HasBaseType("Infrastrcuture.Auth.ApplicationUser");

                    b.Property<int>("numberOfCurrentCases")
                        .HasColumnType("int");

                    b.Property<int>("numberOfEndedCases")
                        .HasColumnType("int");

                    b.Property<int>("numberOfPendingCases")
                        .HasColumnType("int");

                    b.ToTable("Lawyers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7a6a2d33-5d69-4d1e-9ef3-000000000002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b6f994c7-3b9c-45d9-8f3e-666666666666",
                            CreatedAt = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateedBy = "Seed",
                            Email = "abuehab1510@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ABUEHAB1510@GMAIL.COM",
                            NormalizedUserName = "ABUEHAB1510@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGtb0i72XFlbS89FQQKfSVnqluD7460Y6sHBWpYwOE97OBwoCL4WDlVr1r8jjCgezw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6d7c0db6-89af-4e38-bc2e-555555555555",
                            TwoFactorEnabled = false,
                            UserName = "abuehab1510@gmail.com",
                            displayName = "Ahmed Ehab",
                            isActive = true,
                            isDeleted = false,
                            numberOfCurrentCases = 0,
                            numberOfEndedCases = 0,
                            numberOfPendingCases = 0
                        });
                });

            modelBuilder.Entity("Infrastrcuture.Auth.ApplicationUserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("ApplicationUserRole");

                    b.HasData(
                        new
                        {
                            Id = "f5a0a1f3-5f7c-4a35-9b0e-0a9c4f0b0001",
                            ConcurrencyStamp = "9b1b1a9a-4b46-4b2f-9a0e-111111111111",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "f5a0a1f3-5f7c-4a35-9b0e-0a9c4f0b0002",
                            ConcurrencyStamp = "9b1b1a9a-4b46-4b2f-9a0e-222222222222",
                            Name = "Lawyer",
                            NormalizedName = "LAWYER"
                        },
                        new
                        {
                            Id = "f5a0a1f3-5f7c-4a35-9b0e-0a9c4f0b0003",
                            ConcurrencyStamp = "9b1b1a9a-4b46-4b2f-9a0e-333333333333",
                            Name = "Registration Officer",
                            NormalizedName = "REGISTRATION OFFICER"
                        });
                });

            modelBuilder.Entity("Domain.Entites.Case", b =>
                {
                    b.HasOne("Domain.Entites.CaseTopic", "caseTopic")
                        .WithMany("Cases")
                        .HasForeignKey("caseTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entites.CaseType", "caseType")
                        .WithMany("Cases")
                        .HasForeignKey("caseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entites.CourtGrade", "CourtGrade")
                        .WithMany()
                        .HasForeignKey("courtGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Court", "court")
                        .WithMany("Cases")
                        .HasForeignKey("courtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourtGrade");

                    b.Navigation("caseTopic");

                    b.Navigation("caseType");

                    b.Navigation("court");
                });

            modelBuilder.Entity("Domain.Entites.CaseAssignment", b =>
                {
                    b.HasOne("Domain.Entites.Case", "Case")
                        .WithMany("assignments")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastrcuture.Users.Lawyer", null)
                        .WithMany()
                        .HasForeignKey("assignedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Infrastrcuture.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("assignerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Domain.Entites.CaseDocument", b =>
                {
                    b.HasOne("Domain.Entites.Case", "Case")
                        .WithMany("caseDocuments")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Domain.Entites.CaseEvent", b =>
                {
                    b.HasOne("Domain.Entites.Case", "Case")
                        .WithMany("events")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Domain.Entites.CaseLitigant", b =>
                {
                    b.HasOne("Domain.Entites.Case", "Case")
                        .WithMany("CaseLitigants")
                        .HasForeignKey("caseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Litigant", "Litigant")
                        .WithMany("CaseLitigants")
                        .HasForeignKey("litigantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entites.CaseLitigantRole", "Role")
                        .WithMany("CaseLitigants")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Litigant");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entites.Court", b =>
                {
                    b.HasOne("Domain.Entites.CourtGrade", "courtGrade")
                        .WithMany("courts")
                        .HasForeignKey("courtGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("courtGrade");
                });

            modelBuilder.Entity("Domain.Entites.Hearing", b =>
                {
                    b.HasOne("Domain.Entites.Case", "Case")
                        .WithMany("hearings")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Domain.Entites.Judgement", b =>
                {
                    b.HasOne("Domain.Entites.Hearing", "hearing")
                        .WithMany("judgements")
                        .HasForeignKey("hearingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hearing");
                });

            modelBuilder.Entity("Domain.Entites.JudgementOrder", b =>
                {
                    b.HasOne("Domain.Entites.Judgement", "judgement")
                        .WithMany("orders")
                        .HasForeignKey("judgementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("judgement");
                });

            modelBuilder.Entity("Domain.Entites.LegalClaim", b =>
                {
                    b.HasOne("Domain.Entites.Case", "Case")
                        .WithMany("claims")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Domain.Entites.TaskItem", b =>
                {
                    b.HasOne("Domain.Entites.Case", "Case")
                        .WithMany("taskItems")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Infrastrcuture.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Infrastrcuture.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastrcuture.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Infrastrcuture.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastrcuture.Users.Lawyer", b =>
                {
                    b.HasOne("Infrastrcuture.Auth.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Infrastrcuture.Users.Lawyer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entites.Case", b =>
                {
                    b.Navigation("CaseLitigants");

                    b.Navigation("assignments");

                    b.Navigation("caseDocuments");

                    b.Navigation("claims");

                    b.Navigation("events");

                    b.Navigation("hearings");

                    b.Navigation("taskItems");
                });

            modelBuilder.Entity("Domain.Entites.CaseLitigantRole", b =>
                {
                    b.Navigation("CaseLitigants");
                });

            modelBuilder.Entity("Domain.Entites.CaseTopic", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("Domain.Entites.CaseType", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("Domain.Entites.Court", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("Domain.Entites.CourtGrade", b =>
                {
                    b.Navigation("courts");
                });

            modelBuilder.Entity("Domain.Entites.Hearing", b =>
                {
                    b.Navigation("judgements");
                });

            modelBuilder.Entity("Domain.Entites.Judgement", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("Domain.Entites.Litigant", b =>
                {
                    b.Navigation("CaseLitigants");
                });
#pragma warning restore 612, 618
        }
    }
}
